# Site settings
title: Weber
email: vmalloc@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Weber is a project template for ambitious web applications. It includes facilities to develop, test and deploy your code with ease, giving you all the boilerplate you\'ll need to get started quickly
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://getweber.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
